### ISSUE TITLE
There is no DemonCrypt repo available

### ISSUE THREAD

**Issue by leni536** [eijah/demoncrypt#2]
The FAQ states:

> There will be those who are skeptical of such security claims without having access to the source code - I understand and respect your caution. demonsaw's foundation is built off of DemonCrypt, which I've made open-source and available on GitHub.

It's not available yet.

**Comment by n3uromanc3r** [comment]
Yeah, for this to even be considerable, I'm gonna wanna see some sauce.

**Comment by minhoryang** [comment]
+1

**Comment by raivof** [comment]
They have some source code on website, but currently I can't confirm, whether it has valid content. I see some folders with bunch of cpp files and makefiles for Windows and Unix-like platforms. I'll dig in when I arrange time for this task.

Go to:
demonsaw.com -> Download -> section Crypto for Hackers: The Workshop
-> (click on) DEFCON23

And then you get about 90 MB zip file. Confirm Sha1 hash of downloaded file, by using tool sha1sum, or similar.

off-topic, but still.....
"What are your last words to bugs ?"
- "RUN BUGS, RUUUUN !!!" :D

**Comment by mikecardwell** [comment]
From a security point of view, "partially open source" is no better than "closed source". The whole thing should be opened up if you want it to be taken seriously.

**Comment by raivof** [comment]
According to the FAQ:
>Is demonsaw going to be Open Source?
>This was the question that I was most asked at Defcon. Demonsaw's foundation is built off of DemonCrypt, which is open-source and available for free on GitHub (MIT License, also developed by me). Demonsaw itself builds upon DemonCrypt's functionality and creates a graphical interface for users.


- you see, GUI is closed part. Core library seems open. It's the "brainy" part of algorithm, that spreads out the world. GUI is just an interface... They (authors) are making business out of their version of GUI, but I think that anyone who wants, can make alternate interfaces. Cool, no?

But of course, the core open part should be checked out, etc..

**Comment by daveloyall** [comment]
@raivof something doesn't make sense to me.

The website says:
> Keep your wallet happy! No money, no ads, no honeypots, no lies, no bullshit! And, unlike competitors, we aren't in the bitcoin mining business, either :)

If the GUI is closed source so that it can be a product... then what kind of product will it be?

**Comment by raivof** [comment]
That was my first impression/guess about their strategy, why product is partly closed. 

I'm not sure, why they need half closed, half open, if they don't plan to make any money out of this. I admit, it looks a little bit suspicious. It would be interesting, what author says about this. What's the logical deal...

For hackers (not end-users), the core algorithm implementatiopn is the thing in which we are interested.

**Comment by eijah** [comment]
It's bundled up in the "Crypto for Hackers" zip file on the downloads page. Defcon was super crazy and I haven't had a chance to upload it to git yet. I'll upload it to git once I get home tomorrow.
On Aug 10, 2015 3:40 AM, leni536 <notifications@github.com> wrote:The FAQ states:


There will be those who are skeptical of such security claims without having access to the source code - I understand and respect your caution. demonsaw's foundation is built off of DemonCrypt, which I've made open-source and available on GitHub.


It's not available yet.

**Comment by eijah** [comment]
Demoncrypt is bundled up in the "Crypto for Hackers" zip file on the downloads page. Defcon was super crazy and I haven't had a chance to upload it to git yet. I'll upload it to git once I get home tomorrow.
On Aug 10, 2015 5:37 AM, Keito <notifications@github.com> wrote:Yeah, for this to even be considerable, I'm gonna wanna see some sauce.

**Comment by eijah** [comment]
Demoncrypt is bundled up in the "Crypto for Hackers" zip file on the downloads page. Defcon was super crazy and I haven't had a chance to upload it to git yet. I'll upload it to git once I get home tomorrow.
On Aug 10, 2015 5:49 AM, Minho Ryang <notifications@github.com> wrote:+1

**Comment by eijah** [comment]
Demoncrypt is bundled up in the "Crypto for Hackers" zip file on the downloads page. Defcon was super crazy and I haven't had a chance to upload it to git yet. I'll upload it to git once I get home tomorrow.
On Aug 10, 2015 5:51 AM, Raivo Fishmeister <notifications@github.com> wrote:They have some source code on website, but currently I can't confirm, whether it has valid content. I see some folders with bunch of cpp files and makefiles for Windows and Unix-like platforms. I'll dig in when I arrange time for this task.

Go to:
demonsaw.com -> Download -> section Crypto for Hackers: The Workshop
-> (click on) DEFCON23

And then you get about 90 MB zip file. Confirm Sha1 hash of downloaded file, by using tool sha1sum, or similar.

off-topic, but still.....
"What are your last words to bugs ?"

"RUN BUGS, RUUUUN !!!" :D

**Comment by eijah** [comment]
Demoncrypt is bundled up in the "Crypto for Hackers" zip file on the downloads page. Defcon was super crazy and I haven't had a chance to upload it to git yet. I'll upload it to git once I get home tomorrow.
I understand about open source. I'm working two jobs right now and have been burning out lately with my time in demonsaw. Code is not open source 100% yet because I'm trying to get funding for a business version (like metasploit). Just trying to get an opportunity to work on demonsaw full time for you guys.
On Aug 10, 2015 5:58 AM, Mike Cardwell <notifications@github.com> wrote:From a security point of view, "partially open source" is no better than "closed source". The whole thing should be opened up if you want it to be taken seriously.

**Comment by eijah** [comment]
Demoncrypt is bundled up in the "Crypto for Hackers" zip file on the downloads page. Defcon was super crazy and I haven't had a chance to upload it to git yet. I'll upload it to git once I get home tomorrow.
I understand about open source. I'm working two jobs right now and have been burning out lately with my time in demonsaw. Code is not open source 100% yet because I'm trying to get funding for a business version (like metasploit). Just trying to get an opportunity to work on demonsaw full time for you guys.
On Aug 10, 2015 6:02 AM, Raivo Fishmeister <notifications@github.com> wrote:According to the FAQ:


Is demonsaw going to be Open Source?
This was the question that I was most asked at Defcon. Demonsaw's foundation is built off of DemonCrypt, which is open-source and available for free on GitHub (MIT License, also developed by me). Demonsaw itself builds upon DemonCrypt's functionality and creates a graphical interface for users.


you see, GUI is closed part. Core library seems open. It's the "brainy" part of algorithm, that spreads out the world. GUI is just an interface... They (authors) are making business out of their version of GUI, but I think that anyone who wants, can make alternate interfaces. Cool, no?

But of course, the core open part should be checked out, etc..

**Comment by eijah** [comment]
Demoncrypt is bundled up in the "Crypto for Hackers" zip file on the downloads page. Defcon was super crazy and I haven't had a chance to upload it to git yet. I'll upload it to git once I get home tomorrow.
I understand about open source. I'm working two jobs right now and have been burning out lately with my time in demonsaw. Code is not open source 100% yet because I'm trying to get funding for a business version (like metasploit). Just trying to get an opportunity to work on demonsaw full time for you guys.
On Aug 10, 2015 8:36 AM, Dave Loyall <notifications@github.com> wrote:@raivof something doesn't make sense to me.

The website says:


Keep your wallet happy! No money, no ads, no honeypots, no lies, no bullshit! And, unlike competitors, we aren't in the bitcoin mining business, either :)


If the GUI is closed source so that it can be a product... then what kind of product will it be?

**Comment by eijah** [comment]
I understand totally. I am the author. Demonsaw is just me. I do everything. ;-) John Mcafee is my partner but it's totally my company. I have a full time job working with rockstar games and demonsaw is just a hobby. 
On Aug 10, 2015 9:32 AM, Raivo Fishmeister <notifications@github.com> wrote:That was my first impression/guess about their strategy, why product is partly closed. 

I'm not sure, why they need half closed, half open, if they don't plan to make any money out of this. I admit, it looks a little bit suspicious. It would be interesting, what author says about this. What's the logical deal...

For hackers (not end-users), the core algorithm implementatiopn is the thing in which we are interested.

**Comment by eijah** [comment]
I added all the code this morning.  Sorry it took an extra day - still recovering from lack of sleep at Defcon.
